CREATE TABLE movies (
	id VARCHAR(10) NOT NULL DEFAULT '',
	title VARCHAR(100) NOT NULL DEFAULT '',
	year INT NOT NULL,
	director VARCHAR(100) NOT NULL DEFAULT '',
	PRIMARY KEY (id)
);

CREATE TABLE stars (
	id VARCHAR(10) NOT NULL DEFAULT '',
	name VARCHAR(100) NOT NULL DEFAULT '',
	birthYear INT,
	PRIMARY KEY (id)
);

CREATE TABLE stars_in_movies (
	starId VARCHAR(10) NOT NULL DEFAULT '',
	movieId VARCHAR(10) NOT NULL DEFAULT '',
	PRIMARY KEY (starId, movieId),
	FOREIGN KEY (starId) REFERENCES stars(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (movieId) REFERENCES movies(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE genres (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NOT NULL DEFAULT '',
	PRIMARY KEY (id)
);

CREATE TABLE genres_in_movies (
	genreId INT NOT NULL,
	movieId VARCHAR(10) NOT NULL DEFAULT '',
	PRIMARY KEY (genreId, movieId),
	FOREIGN KEY (genreId) REFERENCES genres(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (movieId) REFERENCES movies(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE creditcards (
	id VARCHAR(20) NOT NULL DEFAULT '',
	firstName VARCHAR(50) NOT NULL DEFAULT '',
	lastName VARCHAR(50) NOT NULL DEFAULT '',
	expiration DATE NOT NULL,
	PRIMARY KEY (id)	
);

CREATE TABLE customers (
	id INT NOT NULL AUTO_INCREMENT,
	firstName VARCHAR(50) NOT NULL DEFAULT '',
	lastName VARCHAR(50) NOT NULL DEFAULT '',
	ccId VARCHAR(20) NOT NULL DEFAULT '',
	address VARCHAR(200) NOT NULL DEFAULT '',
	email VARCHAR(50) NOT NULL DEFAULT '',
	password VARCHAR(20) NOT NULL DEFAULT '',
	PRIMARY KEY (id),
	FOREIGN KEY (ccId) REFERENCES creditcards(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE sales (
	id INT NOT NULL AUTO_INCREMENT,
	customerId INT NOT NULL,
	movieId VARCHAR(10) NOT NULL DEFAULT '',
	saleDate DATE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (customerId) REFERENCES customers(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (movieId) REFERENCES movies(id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE ratings (
	movieId VARCHAR(10) NOT NULL DEFAULT '',
	rating FLOAT NOT NULL,
	numVotes INT NOT NULL,
	PRIMARY KEY (movieId),
	FOREIGN KEY (movieId) REFERENCES movies(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX rating
ON ratings(rating);
